version: "3.9"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            env: dev
            REDIS_HOST: redis:6379
            PORT: 80
        depends_on:
            - redis
        #        volumes:
        #            - ./packages/api/build:/home/node/app
        ports:
            - '4223:80'
        #expose:
        #   - 9000

    nginx:
        build:
            context: ./_nginx
            dockerfile: Dockerfile
        #        depends_on:
        #            - api
        ports:
            - '4222:80'

    redis:
        image: redis:6.2.6-alpine
        environment:
            - REDIS_PASSWORD=redis
            #- REDIS_PASSWORD=${REDIS_PASSWORD}
        ports:
            - "4251:6379"
        expose:
            - 4251
#volumes:
#    pg_primary:
